# <!-- Powered by BMAD™ Core -->
# Configuration for MarvelQuant Jainam Prop Integration Completion
# Updated to use /docs/bmad/ for all BMAD-generated documents
markdownExploder: true
qa:
  qaLocation: docs/bmad/qa
prd:
  prdFile: docs/bmad/jainam-prop-completion-prd.md
  prdVersion: v2
  prdSharded: true
  prdShardedLocation: docs/bmad/stories
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: null  # Not needed for integration completion
  architectureVersion: null
  architectureSharded: false
  architectureShardedLocation: docs/bmad/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/bmad/jainam-prop-completion-prd.md
  - docs/broker_factory.md
  - docs/international_broker_integration.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/bmad/stories
slashPrefix: BMad
