# <!-- Powered by BMAD™ Core -->
markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/refactoring-prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/refactoring-architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/project-structure.md
  - docs/architecture/performance-optimization.md
  - docs/refactoring-prd.md
  - docs/refactoring-architecture.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
